//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamManagament_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string department_id { get; set; }
        public string department_name { get; set; }
        public string descriptions { get; set; }
    }
}
